export const LANGUAGE = {
    BANNER_TEXT: {
        TITLE: "SIMS PPOB",
        WELCOME: "SELAMAT DATANG",
        TRANSACTION: {
            BALANCE: "SALDO ANDA",
            SHOW_BALANCE: "LIHAT SALDO"
        },
        PROMO: "TEMUKAN PROMO MENARIK",
        LOGIN_TITLE: "MASUKAN ATAU BUAT AKUN UNTUK MEMULAI",
        REGISTER_TITLE: "LENGKAPI DATA UNTUK MEMBUAT AKUN",
        SERVICE_TOPUP_BANNER: "PEMBAYARAN",
        PLEASE_WELCOME: "SILAHKAN MASUK",
        BALANCE_NOMINAL: "NOMINAL TOP UP",
        ALL_TRANSACTION: "SEMUA TRANSAKSI",
        SHOW_MORE: "SHOW MORE"
    },
    VALIDATION: {
        REQUIRED_FIELD: "FIELD INI WAJIB DIISI",
        PASSWORD_MATCH: "PASSWORD TIDAK SAMA",
        IMAGE_SIZE: "HANYA BISA MENGUPLOAD FILE DENGAN FORMAT JPEG/PNG",
        IMAGE_FORMAT: "UKURAN GAMBAR HARUS LEBIH KECIL DARI 100KB",
        INSUFFICENT_BALANCE: "SALDO TIDAK MENCUKUPI"
    },
    NAVBAR: {
        TOPUP: "TOP UP",
        TRANSACTION: "TRANSACTION",
        AKUN: "AKUN"
    },
    INPUT: {
        PLACEHOLDER: {
            EMAIL: "EMAIL",
            FIRST_NAME: "FIRST NAME",
            LAST_NAME: "LAST NAME",
            PASSWORD: "PASSWORD",
        }
    },
    BUTTON: {
        ACTION_TEXT: {
            EDIT_PROFILE: "EDIT PROFILE",
            LOGOUT: "LOGOUT",
            SIMPAN: "SIMPAN",
            BATAL: "BATAL" 
        }
    }
}